### ISSUE TITLE
Why can't I compile the project?

### ISSUE THREAD

**Issue by BruceWangNo1** [anacrolix/torrent#196]
$go get github.com/anacrolix/torrent/cmd/...
# github.com/anacrolix/torrent/fs
github.com/anacrolix/torrent/fs/file_handle.go:23: cannot use fileHandle literal (type fileHandle) as type interface { Read("golang.org/x/net/context".Context, *fuse.ReadRequest, *fuse.ReadResponse) error; Release("golang.org/x/net/context".Context, *fuse.ReleaseRequest) error } in assignment:
	fileHandle does not implement interface { Read("golang.org/x/net/context".Context, *fuse.ReadRequest, *fuse.ReadResponse) error; Release("golang.org/x/net/context".Context, *fuse.ReleaseRequest) error } (wrong type for Read method)
		have Read("context".Context, *fuse.ReadRequest, *fuse.ReadResponse) error
		want Read("golang.org/x/net/context".Context, *fuse.ReadRequest, *fuse.ReadResponse) error

Anyone to explain this? FYI, it is on Ubuntu 16.04.

**Comment by themihai** [comment]
Try to upgrade to Go 1.9.

**Comment by anacrolix** [comment]
I suspect any Go 1.7+ will work. It looks like 16.04 defaults to 1.6.

**Comment by BruceWangNo1** [comment]
@themihai is right. torrent works with Go 1.9. torrent will fail with Go 1.8. @anacrolix

**Comment by anacrolix** [comment]
Okay thanks. I'll consider any PRs that make earlier versions work.
